export const screenNames = {
  DASHBOARD_SCREEN: 'DASHBOARD_SCREEN',
  MEDICATION_STACK: 'MEDICATION_STACK',
  MEDICATION_SCREEN: 'MEDICATION_SCREEN',
  MEDICATION_DETAILS_SCREEN: 'MEDICATION_DETAILS_SCREEN',
  CALENDAR_SCREEN: 'CALENDAR_SCREEN',
};
